{% set name = "mupdf" %}
{% set version = "1.25.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.mupdf.com/downloads/archive/mupdf-{{ version }}-source.tar.gz
  sha256: 5a51d8bd5ed690d3c8bf82b3c7c3f1cf5f9dde40887a36e3b5aa78a7e3ccd1bb

  patches:
    # Make shared libs, rather than static
    # https://bugs.ghostscript.com/show_bug.cgi?id=702250
    # don't install fully rendered docs
    - Makefile-shared-libs-linux.patch  # [linux]
    - Makefile-shared-libs-osx.patch  # [osx]
    # OSX has libfreetype.a, not libfreetype2.a
    - Makerules.patch  # [osx]
    - wrap.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:   # [osx]
    - /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - cmake  # [win]
    - ninja  # [win]
    - make
    - pkg-config
    - swig
    - python-clang
  host:
    - python
    - xorg-libxfixes  # [linux]
    - libglu  # [linux]
    - libgumbo
    - mesalib  # [unix]
    - freetype
    - jbig2dec
    - openjpeg
    - zlib
    - curl
    - harfbuzz
    - freeglut  # [linux or win]
    - tesseract  # [linux]
    - leptonica  # [linux]
  run:
    - python
    - xorg-libxext  # [linux]
    - xorg-libx11  # [linux]
    - curl

test:
  commands:
    - test -f $PREFIX/bin/mutool  # [unix]
    - if not exist %LIBRARY_BIN%\\mutool.exe exit 1  # [win]
  imports:
    - mupdf  # [linux]

about:
  home: https://www.mupdf.com/
  license: AGPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: A lightweight PDF, XPS, and E-book viewer
  description: |
    The renderer in MuPDF is tailored for high quality anti-aliased graphics.
    It renders text with metrics and spacing accurate to within fractions of
    a pixel for the highest fidelity in reproducing the look of a printed page
    on screen.
  doc_url: https://www.mupdf.com/docs
  dev_url: http://git.ghostscript.com/?p=mupdf.git;a=summary

extra:
  recipe-maintainers:
    - xmnlab
    - scopatz
    - jan-janssen
